apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cart
  labels:
    app: cart
    release: c756
spec:
  namespaceSelector:
    matchNames:
    - c756ns
  selector:
    matchLabels:
      app: cart
  endpoints:
  - port: http
    path: /metrics
