apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cyberdb
  labels:
    app: cyberdb
    release: c756
spec:
  namespaceSelector:
    matchNames:
    - c756ns
  selector:
    matchLabels:
      app: cyberdb
  endpoints:
  - port: http
    path: /metrics
