apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product
  labels:
    app: product
    release: c756
spec:
  namespaceSelector:
    matchNames:
    - c756ns
  selector:
    matchLabels:
      app: product
  endpoints:
  - port: http
    path: /metrics
